version: '3'
services:
  job-portal-api:
    build: .
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/jobportal
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  job-portal-api-dev:
    image: node:20-slim
    volumes:
      - .:/opt/app/
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/jobportal
    command: sh -c "cd /opt/app && corepack enable && pnpm install && pnpm run dev"
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017
